//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type BookSlips struct {
	ID          int32 `sql:"primary_key"`
	PaidAmount  float64
	BookID      *int32
	CreatedByID *int32
	CreatedAt   time.Time
	Buyer       string
	BookName    string
}
