//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Books struct {
	ID        int32 `sql:"primary_key"`
	Name      string
	Bookno    string
	Price     *float64
	Summary   *string
	AuthorID  *int32
	Amount    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
