//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Books = newBooksTable("public", "books", "")

type booksTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnInteger
	Name     postgres.ColumnString
	Bookno   postgres.ColumnString
	Summary  postgres.ColumnString
	AuthorID postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BooksTable struct {
	booksTable

	EXCLUDED booksTable
}

// AS creates new BooksTable with assigned alias
func (a BooksTable) AS(alias string) *BooksTable {
	return newBooksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BooksTable with assigned schema name
func (a BooksTable) FromSchema(schemaName string) *BooksTable {
	return newBooksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BooksTable with assigned table prefix
func (a BooksTable) WithPrefix(prefix string) *BooksTable {
	return newBooksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BooksTable with assigned table suffix
func (a BooksTable) WithSuffix(suffix string) *BooksTable {
	return newBooksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBooksTable(schemaName, tableName, alias string) *BooksTable {
	return &BooksTable{
		booksTable: newBooksTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newBooksTableImpl("", "excluded", ""),
	}
}

func newBooksTableImpl(schemaName, tableName, alias string) booksTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		BooknoColumn   = postgres.StringColumn("bookno")
		SummaryColumn  = postgres.StringColumn("summary")
		AuthorIDColumn = postgres.IntegerColumn("author_id")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn, BooknoColumn, SummaryColumn, AuthorIDColumn}
		mutableColumns = postgres.ColumnList{NameColumn, BooknoColumn, SummaryColumn, AuthorIDColumn}
	)

	return booksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Name:     NameColumn,
		Bookno:   BooknoColumn,
		Summary:  SummaryColumn,
		AuthorID: AuthorIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
