//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BookSlips = newBookSlipsTable("public", "book_slips", "")

type bookSlipsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	PaidAmount  postgres.ColumnFloat
	BookID      postgres.ColumnInteger
	CreatedByID postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	Buyer       postgres.ColumnString
	BookName    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BookSlipsTable struct {
	bookSlipsTable

	EXCLUDED bookSlipsTable
}

// AS creates new BookSlipsTable with assigned alias
func (a BookSlipsTable) AS(alias string) *BookSlipsTable {
	return newBookSlipsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BookSlipsTable with assigned schema name
func (a BookSlipsTable) FromSchema(schemaName string) *BookSlipsTable {
	return newBookSlipsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BookSlipsTable with assigned table prefix
func (a BookSlipsTable) WithPrefix(prefix string) *BookSlipsTable {
	return newBookSlipsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BookSlipsTable with assigned table suffix
func (a BookSlipsTable) WithSuffix(suffix string) *BookSlipsTable {
	return newBookSlipsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBookSlipsTable(schemaName, tableName, alias string) *BookSlipsTable {
	return &BookSlipsTable{
		bookSlipsTable: newBookSlipsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBookSlipsTableImpl("", "excluded", ""),
	}
}

func newBookSlipsTableImpl(schemaName, tableName, alias string) bookSlipsTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		PaidAmountColumn  = postgres.FloatColumn("paid_amount")
		BookIDColumn      = postgres.IntegerColumn("book_id")
		CreatedByIDColumn = postgres.IntegerColumn("created_by_id")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		BuyerColumn       = postgres.StringColumn("buyer")
		BookNameColumn    = postgres.StringColumn("book_name")
		allColumns        = postgres.ColumnList{IDColumn, PaidAmountColumn, BookIDColumn, CreatedByIDColumn, CreatedAtColumn, BuyerColumn, BookNameColumn}
		mutableColumns    = postgres.ColumnList{PaidAmountColumn, BookIDColumn, CreatedByIDColumn, CreatedAtColumn, BuyerColumn, BookNameColumn}
	)

	return bookSlipsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		PaidAmount:  PaidAmountColumn,
		BookID:      BookIDColumn,
		CreatedByID: CreatedByIDColumn,
		CreatedAt:   CreatedAtColumn,
		Buyer:       BuyerColumn,
		BookName:    BookNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
