//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID           int32 `sql:"primary_key"`
	Email        string
	Password     string
	Name         string
	Cash         float64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastSignInAt *time.Time
}
