name: CI

on:
  push:
    branches:
      - main

env:
  MANIFEST_TOKEN: ${{ secrets.MANIFEST_TOKEN }}
  HASH: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: my-go-app
          tags: ${{ env.HASH }}
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: 5822791760/go-api-manifest
          token: ${{ env.MANIFEST_TOKEN }}
          path: .
          persist-credentials: false
          fetch-depth: 0

      - name: Update manifest
        run: |
          sed -i '14s/:latest/:${{ env.HASH }}/' app-base/deployment.yaml

      - name: Commit an push
        uses: actions-js/push@master
        with:
          github_token: ${{ env.MANIFEST_TOKEN }}
          message: "auto-commit-dev-${{ env.HASH }}"
          branch: "main"
